### ISSUE TITLE
Feature request : CircleCi

### ISSUE THREAD

**Issue by benoittgt** [Edouard-chin/ci_runner#3]
Hello

As mention in README
> If your project uses a different CI (Circle, Travis), please open an Issue to let me know you are interested 😸.

I would be very interested to have CircleCI plugged to `ci_runner`.

Also interested to contribute to this.

**Comment by Edouard-chin** [comment]
Hello Benoit 👋 , thanks for opening the issue.

Any chance you could point me to a public project using Circle CI (and if possible with a failing build). I'll use it for implementing that provider. Thanks!

**Comment by benoittgt** [comment]
Hello Edouard

I think this one is a good example https://github.com/thoughtbot/suspenders. Failing build https://github.com/thoughtbot/suspenders/pull/1091

**Comment by Edouard-chin** [comment]
I released v0.2.0 which adds support for Circle CI. https://github.com/Edouard-chin/ci_runner/releases/tag/v0.2.0
You can update the gem by running `gem update ci_runner`.

Going  to close this, but please reopen an issue if something doesn't work :).

**Comment by benoittgt** [comment]
Thank you so much. <3
